Django_project/BookStore/BookStore/urls.py
from django.contrib import admin
from django.urls import path,include
from index.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('test_html/', test_html),
    path('test_if/', test_if),
    path('test_forloop/', test_forloop),
    path('test_filter/', test_filter,name='_filter'),
    path('test_url/<int:id>',test_urls,name='hello'),
    path('base_html/',base_html),
    path('index_html/',index_html),
    path('index/',include('index.urls')),
    path('logincbv/',LoginView.as_view(username="test")),
    path('user/',include('user.urls')),


]

Django_project/BookStore/index/urls.py
from django.urls import path
from index import views
app_name = 'index'
urlpatterns=[
    path('test/',views.index_html,name='detail_hello'),
    path('redict/',views.redict_url),
    path('allbook/',views.BookName),
    path('login_page/',views.login_page),
    path('login/',views.login),
    path('search_title_form/',views.search_ttile_form),
    path('search_title/',views.serch_title),
    path('book_table/',views.book_table),

    ]

Django_project/BookStore/user/urls.py
from django.urls import path
from user import views
urlpatterns=[
    path('reg/',views.reg_view)
]

Django_project/BookStore/index/templates/index/allbook.html
{% for book in books %}
<p>{{book.title}}</p>
{% endfor %}

Django_project/BookStore/index/templates/index/book_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>搜索结果</title>
</head>
<body>
    <li>{{title}}</li>>
</body>
</html>

Django_project/BookStore/index/templates/index/book_table.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>书籍信息表</title>
</head>
<body>
<table border="1">
    <tr>
        <th>id</th>
        <th>title</th>
        <th>price</th>
        <th> retail_price</th>
        <th>public</th>
        <th>option</th>
    </tr>
    {% for book in all_book %}
    <tr>
        <td>{{ book.id }}</td>
        <td>{{ book.title }}</td>
        <td>{{ book.price }}</td>
        <td>{{ book.retail_price }}</td>
        <td>{{ book.pub.pubname }}</td>
        <td>
            <a href="/index/update_book/{{ book.id }}">更新</a>
            <a href="/index/delete_book/{{ book.id }}">删除</a>
        </td>
    </tr>
     {% endfor %}
    </table>
</body>
</html>

Django_project/BookStore/index/templates/index/login.html
<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="UTF-8">
 <title>Login</title>
 <link rel="stylesheet" type="text/css" href="/static/CSS/login.css"/>
</head>
<body>
 <h1>Login</h1>
 <form method="post" action="/index/login/">
  {% csrf_token %}
 <input type="text" required="required" placeholder="用户名" name="username" value="{{ username }}"></input>
 <input type="password" required="required" placeholder="密码" name="password_1" value="{{ password_1 }}"></input>
 <input type="password" required="required" placeholder="密码" name="password_2" value="{{ password_2 }}"></input>
 <button class="but" type="submit">登录</button>
 </form>
</body>
</html>

Django_project/BookStore/index/templates/index/newtest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href=" {% url 'index:detail_hello' %}">点击继续</a>
<p>一起去C语言中文嗨翻天。</p>
</body>
</html>

Django_project/BookStore/index/templates/index/search_title.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>书籍搜索页面</title>
</head>
<body>
{%  if errors  %}
<ul>
    {% for error in errors %}
    <li>
        {{ error }}
    </li>
    {% endfor %}
</ul>
{% endif %}
<form action="/index/search_title/" method="get">
    <input type="text" name="title">
    <input type="submit" value="search_title">
</form>
</body>
</html>